image:
  file: .gitpod.Dockerfile
tasks:
  - sdk install java $(sdk list java | grep -o "8\.[0-9]*\.[0-9]*\.hs-adpt" | head -1)init: |
      sbt compile
    command: |
      sbt ~compile
vscode:
  extensions:
    - scalameta.metals
